# This plugin allows you to break budding amethyst.
# You can allow your players breaking them without silk touch (permission : bba.break) and with (permission : bba.silk);

# If you set to false, you will be able to break them without any permissions.
enable-permissions: true
no-permission: '&cYou do not have the permission to do that!'
reloaded: '&aConfiguration has been reloaded!'